[3] Added login window
agh-educloud/mobile pull request #6
Opened 2019-05-23 20:23 UTC by logx

Ten task mial w sumie sluzyc tylko dodaniu plikow proto ale tak wyszlo ze zaczalem sie bawic UI.

2019-05-29 07:50 UTC, radekoziol requested changes

2019-05-29 07:50 UTC, radekoziol commented on lib/screens/auth/auth.dart
> +class Auth extends StatelessWidget {
Na urządzeniach android nie wyświetla całego widoku

2019-10-07 18:24 UTC, logx commented
<img width="427" alt="Screenshot 2019-10-07 at 20 23 02" src="https://user-images.githubusercontent.com/20932952/66337907-5bde8800-e940-11e9-8735-7ff998fac2d9.png">
<img width="420" alt="Screenshot 2019-10-07 at 20 23 13" src="https://user-images.githubusercontent.com/20932952/66337908-5bde8800-e940-11e9-93d9-254cdb87349a.png">
<img width="437" alt="Screenshot 2019-10-07 at 20 23 26" src="https://user-images.githubusercontent.com/20932952/66337911-5c771e80-e940-11e9-8d32-7f420e7b16ad.png">

2019-10-08 06:42 UTC, radekoziol approved these changes

2019-10-08 06:57 UTC, merged